[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["diffusers"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.black]
line-length = 119
target-version = ['py311']

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501", "C901", "I001"]
select = [
    "C",
    "E",
    "F",
    "I",
    "W",
    "B",
    "Q",
    "UP",
    "ASYNC",
    "N",
    "ANN201",
    "ANN401",
    "ANN205",
    "ANN001",
    "ANN204",
    "ANN202",
]
line-length = 119

[tool.pyright]
typeCheckingMode = "strict"
reportOptionalMemberAccess = false
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportMissingTypeArgument = false
reportUnknownArgumentType = false
reportIncompatibleMethodOverride = false
