DARK_MIDNIGHT_HEX = 0x181825
LIGHT_MIDNIGHT_HEX = 0x1E1E2E
INVISIBLE_EMBED_HEX = 0x2B2D31
RED_HEX = 0xFF0000
PURPLE_HEX = 0x9F27EC

MOON_EMOJI = "🌙"
FIRE_EMOJI = "🔥"
CLOUD_EMOJI = ""
EXPLOSION_EMOJI = "💥"
TRIANGLE_POINTING_RIGHT_EMOJI = "▶️"
TRIANGLE_POINTING_LEFT_EMOJI = "◀️"
PARTY_EMOJI = "🎉"

UNDETECTED_EMOJI = "✅"
DETECTED_EMOJI = "❌"
UPDATING_EMOJI = "🔄"
